version: "3.2"
services:
  connector:
    image: sti/nats-connector:dev
    hostname: nats-connector
    environment:
      gateway_url: http://gateway:8080
      topics: "*"
      print_response: "false"
      basic_auth: "true"
      secret_mount_path: "/run/secrets/"
    secrets:
      - basic-auth-password
      - basic-auth-user
    networks:
      - streaming
      - func_functions

networks:
  streaming:
    driver: overlay
    attachable: true
  func_functions:
    external: true

secrets:
    basic-auth-user:
        external: true
    basic-auth-password:
        external: true